fullnameOverride: go-webapp-mx-dev

config:
  env:
    WEB_APP_ENV: "k8s"
    APP_ENV: "dev"
    APP_COUNTRY: "mx"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/go-webapp-mx-dev-irsa-role

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.name: go-webapp-mx-dev
