{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "go-webapp.fullname" . }}-postgres
  labels:
    {{- include "go-webapp.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ include "go-webapp.secretStoreName" . }}
  target:
    name: {{ include "go-webapp.externalSecretTargetName" . }}
    creationPolicy: {{ .Values.externalSecrets.targetSecret.creationPolicy }}
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecrets.data.username.remoteKey }}
        property: {{ .Values.externalSecrets.data.username.property }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.data.password.remoteKey }}
        property: {{ .Values.externalSecrets.data.password.property }}
{{- end }}
