{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secretStore.create }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "go-webapp.secretStoreName" . }}
  labels:
    {{- include "go-webapp.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: {{ .Values.externalSecrets.secretStore.aws.service }}
      region: {{ .Values.externalSecrets.secretStore.aws.region }}
      {{- if .Values.externalSecrets.secretStore.aws.role }}
      role: {{ .Values.externalSecrets.secretStore.aws.role }}
      {{- end }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "go-webapp.externalSecretsServiceAccountName" . }}
{{- end }}
